# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-05 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='upload_image',
        ),
        migrations.AddField(
            model_name='image',
            name='article_image',
            field=models.ImageField(null=True, upload_to='articles/'),
        ),
    ]
